name: Build libbitcoin-system and Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        architecture: [aarch64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            autoconf \
            libtool \
            pkg-config \
            libboost-all-dev \
            libssl-dev \
            git \
            curl \
            zip

      - name: Install dependencies
        run: |
          # Clone the libbitcoin-system repository
          git clone https://github.com/libbitcoin/libbitcoin-system.git
          cd libbitcoin-system
          
          # Ensure dependencies are updated
          ./autogen.sh
          
          # Configure the build for the target architecture
          ./configure --host=aarch64-linux-gnu --prefix=/usr/local

      - name: Build libbitcoin-system
        run: |
          cd libbitcoin-system
          make -j$(nproc)
          sudo make install

      - name: Create build zip
        run: |
          mkdir -p /tmp/libbitcoin-system
          cp -r /usr/local/* /tmp/libbitcoin-system/
          cd /tmp
          zip -r libbitcoin-system-aarch64.zip libbitcoin-system

      - name: Upload to GoFile API
        run: |
          curl -X POST 'https://store1.gofile.io/contents/uploadfile' \
            -H "Authorization: Bearer ttoDCTma1RmNbzvAH6GG0QJ8tmDNexNi" \
            -F "file=@/tmp/libbitcoin-system-aarch64.zip" \
            -F "folderId=ca1ef56f-9e91-40d4-a914-e0b1ac854702"
            
