name: Build libbitcoin-system and Upload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04  # Use a Linux environment

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install dependencies: Boost, secp256k1, and other build tools
      - name: Install dependencies
        run: |
          # Install system dependencies
          sudo apt update
          sudo apt install -y \
            build-essential \
            autoconf \
            libtool \
            pkg-config \
            curl \
            git \
            libssl-dev \
            libboost-all-dev \
            wget \
            qemu-user-static \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu

          # Install secp256k1 from source
          git clone https://github.com/bitcoin-core/secp256k1.git
          cd secp256k1
          ./autogen.sh
          ./configure --host=aarch64-linux-gnu
          make
          sudo make install
          cd ..

      # Build libbitcoin-system for aarch64
      - name: Build libbitcoin-system for aarch64
        run: |
          # Clone the libbitcoin-system repository
          git clone https://github.com/libbitcoin/libbitcoin-system.git
          cd libbitcoin-system

          # Run the configure script with cross-compilation flags for aarch64
          ./configure --host=aarch64-linux-gnu

          # Compile and build libbitcoin-system
          make -j$(nproc)

      # Create a ZIP file with the build output
      - name: Create ZIP file
        run: |
          cd libbitcoin-system
          zip -r libbitcoin-system.zip .

      # Upload the build ZIP file to GoFile
      - name: Upload to GoFile
        run: |
          curl -X POST 'https://store1.gofile.io/contents/uploadfile' \
          -H "Authorization: Bearer ttoDCTma1RmNbzvAH6GG0QJ8tmDNexNi" \
          -F "file=@libbitcoin-system.zip" \
          -F "folderId=ca1ef56f-9e91-40d4-a914-e0b1ac854702"
          
