name: Install Node.js, Install Packages, and Run main.js

on:
  push:
    branches:
      - main  # or the branch you want to run the workflow on
  pull_request:
    branches:
      - main  # or the branch you want to run the workflow on

jobs:
  install_and_run:
    runs-on: ubuntu-latest  # Use a recent version of Ubuntu
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install NVM (Node Version Manager)
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
          source ~/.bashrc  # Load NVM
          nvm install 22  # Install Node.js version 22
          nvm use 22  # Switch to Node.js version 22
          node -v  # Verify Node.js version
          npm -v   # Verify npm version

      - name: Install dependencies
        run: |
          npm install  # Install required packages from package.json

      - name: Run main.js
        run: |
          node main.js  # Run the main.js file

